version: '3.8'

volumes:
  cs2rarity:  

services:
  fastapi:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
    environment:
      CORS_HOST: http://localhost:3000
      SIGNING_KEY: ${SIGNING_KEY}
      WAIT_HOSTS: db:5432
      WAIT_BEFORE: 5
      WAIT_TIMEOUT: 60
      DATABASE_URL: postgresql://cs2rarityadmin:cs2raritypassword@db/cs2rarity

  db:
    image: postgres:16.1-bullseye
    volumes:
      - cs2rarity:/var/lib/postgresql/data  
    environment:
      POSTGRES_PASSWORD: cs2raritypassword
      POSTGRES_USER: cs2rarityadmin
      POSTGRES_DB: cs2rarity
    ports:
      - "15432:5432"