volumes:
  cs2rarity:
    external: true
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    environment:
      CORS_HOST: http://localhost:3000
      SIGNING_KEY: ${SIGNING_KEY}
      WAIT_HOSTS: db:5432
      WAIT_BEFORE: 5
      WAIT_TIMEOUT: 60
      PORT: 8000
      DATABASE_URL: postgresql://cs2rarityadmin:cs2raritypassword@db/cs2rarity
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
  db:
    image: postgres:16.1-bullseye
    environment:
      POSTGRES_PASSWORD: cs2raritypassword
      POSTGRES_USER: cs2rarityadmin
      POSTGRES_DB: cs2rarity
    ports:
      - "15432:5432"
    volumes:
      - cs2rarity:/var/lib/postgresql/data
