FROM python:3.10-bullseye
RUN python -m pip install --upgrade pip

ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.9.0/wait /wait
RUN chmod +x /wait

WORKDIR /app
COPY requirements.txt requirements.txt
COPY main.py main.py
COPY migrations migrations
COPY models models
COPY queries queries
COPY routers routers
COPY authenticator.py authenticator.py
RUN python -m pip install -r requirements.txt

WORKDIR /app
CMD /wait && python -m migrations up && uvicorn main:app --reload --host 0.0.0.0